
package com.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IWeatherImplService", targetNamespace = "http://webservice.com/", wsdlLocation = "http://127.0.0.1:12345/weather?wsdl")
public class IWeatherImplService
    extends Service
{

    private final static URL IWEATHERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IWEATHERIMPLSERVICE_EXCEPTION;
    private final static QName IWEATHERIMPLSERVICE_QNAME = new QName("http://webservice.com/", "IWeatherImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:12345/weather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IWEATHERIMPLSERVICE_WSDL_LOCATION = url;
        IWEATHERIMPLSERVICE_EXCEPTION = e;
    }

    public IWeatherImplService() {
        super(__getWsdlLocation(), IWEATHERIMPLSERVICE_QNAME);
    }

    public IWeatherImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IWEATHERIMPLSERVICE_QNAME, features);
    }

    public IWeatherImplService(URL wsdlLocation) {
        super(wsdlLocation, IWEATHERIMPLSERVICE_QNAME);
    }

    public IWeatherImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IWEATHERIMPLSERVICE_QNAME, features);
    }

    public IWeatherImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IWeatherImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWeatherImpl
     */
    @WebEndpoint(name = "IWeatherImplPort")
    public IWeatherImpl getIWeatherImplPort() {
        return super.getPort(new QName("http://webservice.com/", "IWeatherImplPort"), IWeatherImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWeatherImpl
     */
    @WebEndpoint(name = "IWeatherImplPort")
    public IWeatherImpl getIWeatherImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.com/", "IWeatherImplPort"), IWeatherImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IWEATHERIMPLSERVICE_EXCEPTION!= null) {
            throw IWEATHERIMPLSERVICE_EXCEPTION;
        }
        return IWEATHERIMPLSERVICE_WSDL_LOCATION;
    }

}
